// Automatisch generiert aus Arabic-Roots-Daten (Kapitel 1-9, Madina Buch 1) + persoenliche Vokabeln
const VOCAB_DATA = [
 {
  "id": "45751",
  "ar": "بَيْتٌ",
  "de": "Haus",
  /* Elias am 04.08.2026: „Vers (Poesie)" sei falsch. Es ist nicht falsch — die
     Angabe steht wortgleich in seinem eigenen arabicroots-Abzug
     (data/vokabeln-madina-1.js Z. 9) und wird dort vom zweiten Plural
     أَبْيَاتٌ gestützt, genau dem Plural für Verszeilen. Gelöscht wird sie
     deshalb nicht (Regel 7a: bezahlter Abzug wird nicht still überschrieben).
     Sie steht jetzt aber nicht mehr in der Antwortzeile, sondern als
     Nebenbedeutung darunter — in Lektion 1 heißt بَيْتٌ schlicht „Haus".
     Nebenbei war das (1)…(2)-Muster die einzige Ausnahme unter 171 Vokabeln;
     alle anderen Mehrfachbedeutungen schreiben „A / B". */
  "deNeben": "Vers (Poesie)",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "بَيْتٌ",
  "pl": "بُيُوتٌ / أَبْيَاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "ب ي ت",
  "sentAr": "هَذَا بَيْتٌ جَمِيلٌ وَنَظِيفٌ.",
  "sentDe": "Dies ist ein schönes und sauberes Haus.",
  "quran": {
   "surah": "Al-Baqarah",
   "ayah": "2:125",
   "ar": "وَإِذْ جَعَلْنَا الْبَيْتَ مَثَابَةً لِلنَّاسِ وَأَمْنًا",
   "de": "Und als Wir das Haus zu einem Sammelpunkt für die Menschen und einem sicheren Ort machten.",
   "note": "Al-Bayt bezeichnet hier die Kaaba. Geprüft gegen quran.com."
  },
  "source": "vocabulary",
  "box": 5,
  "acc": 92
 },
 {
  "id": "45752",
  "ar": "مَسْجِدٌ",
  "de": "Moschee",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "مَسْجِدٌ",
  "pl": "مَسَاجِدُ",
  "femSg": null,
  "femPl": null,
  "root": "س ج د",
  "sentAr": "هَذَا مَسْجِدٌ جَدِيدٌ قَرِيبٌ مِنَ الْبَيْتِ.",
  "sentDe": "Dies ist eine neue Moschee, nahe am Haus.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 98
 },
 {
  "id": "45753",
  "ar": "بَابٌ",
  "de": "Tür",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "بَابٌ",
  "pl": "أَبْوَابٌ",
  "femSg": null,
  "femPl": null,
  "root": "ب و ب",
  "sentAr": "بَابُ الْبَيْتِ جَدِيدٌ.",
  "sentDe": "Die Tür des Hauses ist neu.",
  "quran": {
   "surah": "Al-Hijr",
   "ayah": "15:44",
   "ar": "لَهَا سَبْعَةُ أَبْوَٰبٍ لِّكُلِّ بَابٍ مِّنْهُمْ جُزْءٌ مَّقْسُومٌ",
   "de": "Sie hat sieben Tore, und jedem Tor wird ein Teil von ihnen zugewiesen",
   "note": null
  },
  "source": "vocabulary",
  "box": 5,
  "acc": 97
 },
 {
  "id": "45754",
  "ar": "كِتَابٌ",
  "de": "Buch",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "كِتَابٌ",
  "pl": "كُتُبٌ",
  "femSg": null,
  "femPl": null,
  "root": "ك ت ب",
  "sentAr": "هَذَا كِتَابٌ قَدِيمٌ وَثَقِيلٌ.",
  "sentDe": "Dies ist ein altes und schweres Buch.",
  "quran": {
   "surah": "Al-Baqarah",
   "ayah": "2:2",
   "ar": "ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ",
   "de": "Dieses Buch, an dem es keinen Zweifel gibt, ist eine Rechtleitung für die Gottesfürchtigen.",
   "note": "Berühmter Vers direkt nach Al-Fatiha. Geprüft gegen quran.com."
  },
  "source": "vocabulary",
  "box": 5,
  "acc": 98
 },
 {
  "id": "45755",
  "ar": "قَلَمٌ",
  "de": "Stift",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "قَلَمٌ",
  "pl": "أَقْلَامٌ",
  "femSg": null,
  "femPl": null,
  "root": "ق ل م",
  "sentAr": "هَذَا قَلَمٌ صَغِيرٌ عَلَى الْمَكْتَبِ.",
  "sentDe": "Dies ist ein kleiner Stift auf dem Schreibtisch.",
  "quran": {
   "surah": "Al-Qalam",
   "ayah": "68:1",
   "ar": "ن ۚ وَالْقَلَمِ وَمَا يَسْطُرُونَ",
   "de": "Nun. Beim Schreibrohr und dem, was sie in Zeilen niederschreiben.",
   "note": "Eroeffnungsvers der Sure Al-Qalam. Geprueft gegen quran.com."
  },
  "source": "vocabulary",
  "box": 5,
  "acc": 98
 },
 {
  "id": "45756",
  "ar": "مِفْتَاحٌ",
  "de": "Schlüssel",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "مِفْتَاحٌ",
  "pl": "مَفَاتِيحُ",
  "femSg": null,
  "femPl": null,
  "root": "ف ت ح",
  "sentAr": "مِفْتَاحُ الْبَابِ فِي الْحَقِيبَةِ.",
  "sentDe": "Der Schlüssel der Tür ist in der Tasche.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 80
 },
 {
  "id": "45757",
  "ar": "مَكْتَبٌ",
  "de": "Schreibtisch / Büro / Amt",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "مَكْتَبٌ",
  "pl": "مَكَاتِبُ",
  "femSg": null,
  "femPl": null,
  "root": "ك ت ب",
  "sentAr": "هَذَا مَكْتَبٌ جَدِيدٌ فِي الْمَدْرَسَةِ.",
  "sentDe": "Dies ist ein neuer Schreibtisch in der Schule.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 72
 },
 {
  "id": "45758",
  "ar": "سَرِيرٌ",
  "de": "Bett",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "سَرِيرٌ",
  "pl": "أَسِرَّةٌ",
  "femSg": null,
  "femPl": null,
  "root": "س ر ر",
  "sentAr": "هَذَا سَرِيرٌ صَغِيرٌ فِي الْغُرْفَةِ.",
  "sentDe": "Dies ist ein kleines Bett im Zimmer.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 66
 },
 {
  "id": "45759",
  "ar": "كُرْسِيٌّ",
  "de": "Stuhl",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "كُرْسِيٌّ",
  "pl": "كَرَاسِيُّ",
  "femSg": null,
  "femPl": null,
  "root": "ك ر س",
  "sentAr": "هَذَا كُرْسِيٌّ قَدِيمٌ وَثَقِيلٌ.",
  "sentDe": "Dies ist ein alter und schwerer Stuhl.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 99
 },
 {
  "id": "45760",
  "ar": "نَجْمٌ",
  "de": "Stern",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "نَجْمٌ",
  "pl": "نُجُومٌ",
  "femSg": null,
  "femPl": null,
  "root": "ن ج م",
  "sentAr": "هَذَا نَجْمٌ بَعِيدٌ فِي السَّمَاءِ.",
  "sentDe": "Dies ist ein ferner Stern am Himmel.",
  "quran": {
   "surah": "An-Najm",
   "ayah": "53:1",
   "ar": "وَالنَّجْمِ إِذَا هَوَىٰ",
   "de": "Bei dem Stern, wenn er sinkt!",
   "note": "Eroeffnungsvers der Sure An-Najm. Geprueft gegen quran.com."
  },
  "source": "vocabulary",
  "box": 3,
  "acc": 68
 },
 {
  "id": "45761",
  "ar": "طَبِيبٌ",
  "de": "Arzt",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "طَبِيبٌ",
  "pl": "أَطِبَّاءُ",
  "femSg": "طَبِيبَةٌ",
  "femPl": "طَبِيبَاتٌ",
  "root": "ط ب ب",
  "sentAr": "الطَّبِيبُ فِي الْمُسْتَشْفَى الْآنَ.",
  "sentDe": "Der Arzt ist jetzt im Krankenhaus.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 62
 },
 {
  "id": "45762",
  "ar": "وَلَدٌ",
  "de": "Junge",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "وَلَدٌ",
  "pl": "أَوْلَادٌ",
  "femSg": null,
  "femPl": null,
  "root": "و ل د",
  "sentAr": "هَذَا وَلَدٌ مُجْتَهِدٌ.",
  "sentDe": "Dies ist ein fleißiger Junge.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 84
 },
 {
  "id": "45763",
  "ar": "طَالِبٌ",
  "de": "Student",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "طَالِبٌ",
  "pl": "طُلَّابٌ",
  "femSg": "طَالِبَةٌ",
  "femPl": "طَالِبَاتٌ",
  "root": "ط ل ب",
  "sentAr": "هَذَا طَالِبٌ فِي الْجَامِعَةِ.",
  "sentDe": "Dies ist ein Student an der Universität.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 89
 },
 {
  "id": "45764",
  "ar": "رَجُلٌ",
  "de": "Mann",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "رَجُلٌ",
  "pl": "رِجَالٌ",
  "femSg": null,
  "femPl": null,
  "root": "ر ج ل",
  "sentAr": "هَذَا رَجُلٌ غَنِيٌّ وَمَشْهُورٌ.",
  "sentDe": "Dies ist ein reicher und berühmter Mann.",
  "quran": {
   "surah": "Al-Mu'minun",
   "ayah": "23:25",
   "ar": "إِنْ هُوَ إِلَّا رَجُلُۢ بِهِۦ جِنَّةٌ فَتَرَبَّصُواْ بِهِۦ حَتَّىٰ حِينٍ‏",
   "de": "Er ist nur ein Mann, der an Besessenheit leidet; so wartet mit ihm für eine gewisse Zeit ab",
   "note": null
  },
  "source": "vocabulary",
  "box": 5,
  "acc": 91
 },
 {
  "id": "45765",
  "ar": "تَاجِرٌ",
  "de": "Händler",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "تَاجِرٌ",
  "pl": "تُجَّارٌ",
  "femSg": "تَاجِرَةٌ",
  "femPl": "تَاجِرَاتٌ",
  "root": "ت ج ر",
  "sentAr": "التَّاجِرُ فِي السُّوقِ الْآنَ.",
  "sentDe": "Der Händler ist jetzt auf dem Markt.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 58
 },
 {
  "id": "45766",
  "ar": "كَلْبٌ",
  "de": "Hund",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "كَلْبٌ",
  "pl": "كِلَابٌ",
  "femSg": "كَلْبَةٌ",
  "femPl": "كَلْبَاتٌ",
  "root": "ك ل ب",
  "sentAr": "هَذَا كَلْبٌ صَغِيرٌ وَسَرِيعٌ.",
  "sentDe": "Dies ist ein kleiner und schneller Hund.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 97
 },
 {
  "id": "45767",
  "ar": "قِطٌّ",
  "de": "Katze",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "قِطٌّ",
  "pl": "قِطَطٌ",
  "femSg": "قِطَّةٌ",
  "femPl": "قِطَطٌ",
  "root": "ق ط ط",
  "sentAr": "هَذَا قِطٌّ جَمِيلٌ تَحْتَ السَّرِيرِ.",
  "sentDe": "Dies ist eine schöne Katze unter dem Bett.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 89
 },
 {
  "id": "45768",
  "ar": "حِمَارٌ",
  "de": "Esel",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "حِمَارٌ",
  "pl": "حُمُرٌ",
  "femSg": null,
  "femPl": null,
  "root": "ح م ر",
  "sentAr": "هَذَا حِمَارٌ مَرِيضٌ قَرِيبٌ مِنَ الْبَيْتِ.",
  "sentDe": "Dies ist ein kranker Esel, nahe am Haus.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 85
 },
 {
  "id": "45769",
  "ar": "حِصَانٌ",
  "de": "Pferd",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "حِصَانٌ",
  "pl": "أَحْصِنَةٌ",
  "femSg": null,
  "femPl": null,
  "root": "ح ص ن",
  "sentAr": "هَذَا حِصَانٌ سَرِيعٌ وَجَمِيلٌ.",
  "sentDe": "Dies ist ein schnelles und schönes Pferd.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 79
 },
 {
  "id": "45770",
  "ar": "جَمَلٌ",
  "de": "Kamel",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "جَمَلٌ",
  "pl": "جِمَالٌ",
  "femSg": null,
  "femPl": null,
  "root": "ج م ل",
  "sentAr": "هَذَا جَمَلٌ طَوِيلٌ وَجَمِيلٌ.",
  "sentDe": "Dies ist ein hohes und schönes Kamel.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 78
 },
 {
  "id": "45771",
  "ar": "دِيكٌ",
  "de": "Hahn",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "دِيكٌ",
  "pl": "دُيُوكٌ",
  "femSg": null,
  "femPl": null,
  "root": "د ي ك",
  "sentAr": "هَذَا دِيكٌ جَمِيلٌ قَرِيبٌ مِنَ الْبَيْتِ.",
  "sentDe": "Dies ist ein schöner Hahn, nahe am Haus.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 72
 },
 {
  "id": "45772",
  "ar": "مُدَرِّسٌ",
  "de": "Lehrer",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "مُدَرِّسٌ",
  "pl": "مُدَرِّسُونَ",
  "femSg": "مُدَرِّسَةٌ",
  "femPl": "مُدَرِّسَاتٌ",
  "root": "د ر س",
  "sentAr": "هَذَا مُدَرِّسٌ مُجْتَهِدٌ فِي الثَّانَوِيَّةِ.",
  "sentDe": "Dies ist ein fleißiger Lehrer an der weiterführenden Schule.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 69
 },
 {
  "id": "45773",
  "ar": "مِنْدِيلٌ",
  "de": "Tuch",
  "type": "noun",
  "chapter": 1,
  "gender": "masculine",
  "sg": "مِنْدِيلٌ",
  "pl": "مَنَادِيلُ",
  "femSg": null,
  "femPl": null,
  "root": "م ن د ل",
  "sentAr": "هَذَا مِنْدِيلٌ نَظِيفٌ فِي الْحَقِيبَةِ.",
  "sentDe": "Dies ist ein sauberes Tuch in der Tasche.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 70
 },
 {
  "id": "45774",
  "ar": "نَعَمْ",
  "de": "ja",
  "type": "particle",
  "chapter": 1,
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "أَهَذَا كِتَابٌ؟ نَعَمْ، هَذَا كِتَابٌ.",
  "sentDe": "Ist dies ein Buch? Ja, dies ist ein Buch.",
  "quran": {
   "surah": "As-Saffat",
   "ayah": "37:18",
   "ar": "قُلْ نَعَمْ وَأَنتُمْ دَٰخِرُونَ",
   "de": "Sag: Ja, und ihr werdet euch demütig verhalten",
   "note": null
  },
  "source": "vocabulary",
  "box": 5,
  "acc": 98
 },
 {
  "id": "45775",
  "ar": "لَا",
  "de": "nein",
  "type": "particle",
  "chapter": 1,
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "أَهَذَا مَسْجِدٌ؟ لَا، هَذَا بَيْتٌ.",
  "sentDe": "Ist dies eine Moschee? Nein, dies ist ein Haus.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 98
 },
 {
  "id": "45776",
  "ar": "أَ",
  "de": "Fragepartikel",
  "type": "particle",
  "chapter": 1,
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "أَهَذَا قَلَمٌ؟",
  "sentDe": "Ist dies ein Stift?",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 92
 },
 {
  "id": "45777",
  "ar": "مَا",
  "de": "was",
  "type": "particle",
  "chapter": 1,
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "مَا هَذَا؟ هَذَا كِتَابٌ.",
  "sentDe": "Was ist das? Das ist ein Buch.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 87
 },
 {
  "id": "45778",
  "ar": "وَ",
  "de": "und",
  "type": "particle",
  "chapter": 1,
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "هَذَا قَلَمٌ وَكِتَابٌ.",
  "sentDe": "Dies ist ein Stift und ein Buch.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 98
 },
 {
  "id": "45779",
  "ar": "إِمَامٌ",
  "de": "Imam",
  "type": "noun",
  "chapter": 2,
  "gender": "masculine",
  "sg": "إِمَامٌ",
  "pl": "أَئِمَّةٌ",
  "femSg": "إِمَامَةٌ",
  "femPl": "إِمَامَاتٌ",
  "root": "أ م م",
  "sentAr": "مَنْ ذَلِكَ؟ ذَلِكَ إِمَامٌ.",
  "sentDe": "Wer ist jener? Jener ist ein Imam.",
  "quran": {
   "surah": "Al-Baqarah",
   "ayah": "2:124",
   "ar": "إِنِّي جَاعِلُكَ لِلنَّاسِ إِمَامًا",
   "de": "Ich will dich zu einem Vorbild fuer die Menschen machen.",
   "note": "Allah spricht zu Ibrahim (a.s.). Geprueft gegen quran.com."
  },
  "source": "vocabulary",
  "box": 5,
  "acc": 98
 },
 {
  "id": "45780",
  "ar": "حَجَرٌ",
  "de": "Stein",
  "type": "noun",
  "chapter": 2,
  "gender": "masculine",
  "sg": "حَجَرٌ",
  "pl": "حِجَارَةٌ",
  "femSg": null,
  "femPl": null,
  "root": "ح ج ر",
  "sentAr": "هَذَا حَجَرٌ قَدِيمٌ وَثَقِيلٌ.",
  "sentDe": "Dies ist ein alter und schwerer Stein.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 70
 },
 {
  "id": "45781",
  "ar": "سُكَّرٌ",
  "de": "Zucker",
  "type": "noun",
  "chapter": 2,
  "gender": "masculine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "س ك ر",
  "sentAr": "هَذَا سُكَّرٌ وَذَلِكَ لَبَنٌ.",
  "sentDe": "Dies ist Zucker und jenes ist Milch.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 98
 },
 {
  "id": "45782",
  "ar": "لَبَنٌ",
  "de": "Milch",
  "type": "noun",
  "chapter": 2,
  "gender": "masculine",
  "sg": null,
  "pl": "أَلْبَان",
  "femSg": null,
  "femPl": null,
  "root": "ل ب ن",
  "sentAr": "هَذَا لَبَنٌ حُلْوٌ وَبَارِدٌ.",
  "sentDe": "Dies ist süße und kalte Milch.",
  "quran": {
   "surah": "Muhammad",
   "ayah": "47:15",
   "ar": "وَأَنْهَارٌ مِنْ لَبَنٍ لَمْ يَتَغَيَّرْ طَعْمُهُ",
   "de": "...und Baeche mit Milch, deren Geschmack sich nicht aendert...",
   "note": "Beschreibung der Fluesse im Paradies. Geprueft gegen quran.com."
  },
  "source": "vocabulary",
  "box": 4,
  "acc": 75
 },
 {
  "id": "45783",
  "ar": "غَنِيٌّ",
  "de": "reich",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "غَنِيٌّ",
  "pl": "أَغْنِيَاءُ",
  "femSg": "غَنِيَّةٌ",
  "femPl": "غَنِيَّاتٌ",
  "root": "غ ن ي",
  "sentAr": "هَذَا التَّاجِرُ غَنِيٌّ وَمَشْهُورٌ.",
  "sentDe": "Dieser Händler ist reich und berühmt.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 82
 },
 {
  "id": "45784",
  "ar": "فَقِيرٌ",
  "de": "arm",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "فَقِيرٌ",
  "pl": "فُقَرَاءُ",
  "femSg": "فَقِيرَةٌ",
  "femPl": "فَقِيرَاتٌ",
  "root": "ف ق ر",
  "sentAr": "هَذَا الرَّجُلُ فَقِيرٌ.",
  "sentDe": "Dieser Mann ist arm.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 78
 },
 {
  "id": "45785",
  "ar": "طَوِيلٌ",
  "de": "groß (lang)",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "طَوِيلٌ",
  "pl": "طِوَالٌ",
  "femSg": "طَوِيلَةٌ",
  "femPl": "طَوِيلَاتٌ",
  "root": "ط و ل",
  "sentAr": "هَذَا الشَّارِعُ طَوِيلٌ.",
  "sentDe": "Diese Straße ist lang.",
  "quran": {
   "surah": "Al-Muzzammil",
   "ayah": "73:7",
   "ar": "إِنَّ لَكَ فِي ٱلنَّهَارِ سَبْحًا طَوِيلًا",
   "de": "Du hast ja am Tage lange Zeit für Beschäftigung",
   "note": null
  },
  "source": "vocabulary",
  "box": 3,
  "acc": 63
 },
 {
  "id": "45786",
  "ar": "قَصِيرٌ",
  "de": "kurz",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "قَصِيرٌ",
  "pl": "قِصَارٌ",
  "femSg": "قَصِيرَةٌ",
  "femPl": "قَصِيرَاتٌ",
  "root": "ق ص ر",
  "sentAr": "هَذَا الْقَلَمُ قَصِيرٌ.",
  "sentDe": "Dieser Stift ist kurz.",
  "quran": null,
  "mnemo": "Merke die Wurzel, nicht das Wort: ق ص ر trägt die Bedeutung „kurz/knapp\" durch alle Formen.",
  "source": "vocabulary",
  "box": 2,
  "acc": 48
 },
 {
  "id": "45787",
  "ar": "بَارِدٌ",
  "de": "kalt",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "بَارِدٌ",
  "pl": "بَارِدُونَ",
  "femSg": "بَارِدَةٌ",
  "femPl": "بَارِدَاتٌ",
  "root": "ب ر د",
  "sentAr": "الْمَاءُ بَارِدٌ الْيَوْمَ.",
  "sentDe": "Das Wasser ist heute kalt.",
  "quran": {
   "surah": "Al-Waqi'ah",
   "ayah": "56:44",
   "ar": "لَّا بَارِدٍ وَلَا كَرِيمٍ",
   "de": "(der) weder kühl noch trefflich (ist)",
   "note": null
  },
  "source": "vocabulary",
  "box": 3,
  "acc": 61
 },
 {
  "id": "45788",
  "ar": "حَارٌّ",
  "de": "heiß",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "حَارٌّ",
  "pl": "حَارُّونَ",
  "femSg": "حَارَّةٌ",
  "femPl": "حَارَّاتٌ",
  "root": "ح ر ر",
  "sentAr": "الشَّايُ حَارٌّ.",
  "sentDe": "Der Tee ist heiß.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 71
 },
 {
  "id": "45789",
  "ar": "جَالِسٌ",
  "de": "sitzend",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "جَالِسٌ",
  "pl": "جَالِسُونَ",
  "femSg": "جَالِسَةٌ",
  "femPl": "جَالِسَاتٌ",
  "root": "ج ل س",
  "sentAr": "الطَّالِبُ جَالِسٌ عَلَى الْكُرْسِيِّ.",
  "sentDe": "Der Student sitzt auf dem Stuhl.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 51
 },
 {
  "id": "45790",
  "ar": "وَاقِفٌ",
  "de": "stehend",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "وَاقِفٌ",
  "pl": "وَاقِفُونَ",
  "femSg": "وَاقِفَةٌ",
  "femPl": "وَاقِفَاتٌ",
  "root": "و ق ف",
  "sentAr": "الْوَلَدُ وَاقِفٌ قَرِيبٌ مِنَ الْبَابِ.",
  "sentDe": "Der Junge steht nahe an der Tür.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 54
 },
 {
  "id": "45791",
  "ar": "جَدِيدٌ",
  "de": "neu",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "جَدِيدٌ",
  "pl": "جُدُدٌ",
  "femSg": "جَدِيدَةٌ",
  "femPl": "جَدِيدَاتٌ",
  "root": "ج د د",
  "sentAr": "هَذَا الْكِتَابُ جَدِيدٌ.",
  "sentDe": "Dieses Buch ist neu.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 60
 },
 {
  "id": "45792",
  "ar": "قَدِيمٌ",
  "de": "alt",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "قَدِيمٌ",
  "pl": "قُدَمَاءُ",
  "femSg": "قَدِيمَةٌ",
  "femPl": "قَدِيمَاتٌ",
  "root": "ق د م",
  "sentAr": "هَذَا الْمَسْجِدُ قَدِيمٌ وَمَشْهُورٌ.",
  "sentDe": "Diese Moschee ist alt und berühmt.",
  "quran": {
   "surah": "Yusuf",
   "ayah": "12:95",
   "ar": "قَالُواْ تَٱللَّهِ إِنَّكَ لَفِي ضَلَٰلِكَ ٱلْقَدِيمِ",
   "de": "Sie sagten: Bei Allah, du befindest dich fürwahr in deinem alten Irrtum",
   "note": null
  },
  "source": "vocabulary",
  "box": 3,
  "acc": 61
 },
 {
  "id": "45793",
  "ar": "قَرِيبٌ",
  "de": "nah",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "قَرِيبٌ",
  "pl": "قَرِيبُونَ",
  "femSg": "قَرِيبَةٌ",
  "femPl": "قَرِيبَاتٌ",
  "root": "ق ر ب",
  "sentAr": "الْمَدْرَسَةُ قَرِيبَةٌ مِنَ الْبَيْتِ.",
  "sentDe": "Die Schule ist nahe am Haus.",
  "quran": {
   "surah": "Al-Ma'arij",
   "ayah": "70:7",
   "ar": "وَنَرَىٰهُ قَرِيبًا",
   "de": "Wir aber sehen sie nahe",
   "note": null
  },
  "source": "vocabulary",
  "box": 3,
  "acc": 55
 },
 {
  "id": "45794",
  "ar": "بَعِيدٌ",
  "de": "fern",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "بَعِيدٌ",
  "pl": "بَعِيدُونَ",
  "femSg": "بَعِيدَةٌ",
  "femPl": "بَعِيدَاتٌ",
  "root": "ب ع د",
  "sentAr": "الْجَامِعَةُ بَعِيدَةٌ مِنَ الْبَيْتِ.",
  "sentDe": "Die Universität ist weit vom Haus entfernt.",
  "quran": {
   "surah": "Al-Ma'arij",
   "ayah": "70:6",
   "ar": "إِنَّهُمْ يَرَوْنَهُۥ بَعِيدًا",
   "de": "Gewiß, sie sehen sie weit entfernt",
   "note": null
  },
  "source": "vocabulary",
  "box": 3,
  "acc": 58
 },
 {
  "id": "45795",
  "ar": "نَظِيفٌ",
  "de": "sauber",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "نَظِيفٌ",
  "pl": "نَظِيفُونَ",
  "femSg": "نَظِيفَةٌ",
  "femPl": "نَظِيفَاتٌ",
  "root": "ن ظ ف",
  "sentAr": "هَذَا الْمِنْدِيلُ نَظِيفٌ.",
  "sentDe": "Dieses Tuch ist sauber.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 59
 },
 {
  "id": "45796",
  "ar": "وَسِخٌ",
  "de": "schmutzig",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "وَسِخٌ",
  "pl": "وَسِخُونَ",
  "femSg": "وَسِخَةٌ",
  "femPl": "وَسِخَاتٌ",
  "root": "و س خ",
  "sentAr": "هَذَا الْكَلْبُ وَسِخٌ.",
  "sentDe": "Dieser Hund ist schmutzig.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 58
 },
 {
  "id": "45797",
  "ar": "صَغِيرٌ",
  "de": "klein",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "صَغِيرٌ",
  "pl": "صِغَارٌ",
  "femSg": "صَغِيرَةٌ",
  "femPl": "صَغِيرَاتٌ",
  "root": "ص غ ر",
  "sentAr": "هَذَا الْقِطُّ صَغِيرٌ وَجَمِيلٌ.",
  "sentDe": "Diese Katze ist klein und schön.",
  "quran": {
   "surah": "Al-Qamar",
   "ayah": "54:53",
   "ar": "وَكُلُّ صَغِيرٍ وَكَبِيرٍ مُّسْتَطَرٌ",
   "de": "Alles, ob klein oder groß, wird in Zeilen niedergeschrieben",
   "note": null
  },
  "source": "vocabulary",
  "box": 3,
  "acc": 60
 },
 {
  "id": "45798",
  "ar": "كَبِيرٌ",
  "de": "groß",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "كَبِيرٌ",
  "pl": "كِبَارٌ",
  "femSg": "كَبِيرَةٌ",
  "femPl": "كَبِيرَاتٌ",
  "root": "ك ب ر",
  "sentAr": "الْمَسْجِدُ كَبِيرٌ وَجَمِيلٌ.",
  "sentDe": "Die Moschee ist groß und schön.",
  "quran": {
   "surah": "Al-Qamar",
   "ayah": "54:53",
   "ar": "وَكُلُّ صَغِيرٍ وَكَبِيرٍ مُّسْتَطَرٌ",
   "de": "Alles, ob klein oder groß, wird in Zeilen niedergeschrieben",
   "note": null
  },
  "source": "vocabulary",
  "box": 4,
  "acc": 80
 },
 {
  "id": "45799",
  "ar": "خَفِيفٌ",
  "de": "leicht",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "خَفِيفٌ",
  "pl": "خِفَافٌ",
  "femSg": "خَفِيفَةٌ",
  "femPl": "خَفِيفَاتٌ",
  "root": "خ ف ف",
  "sentAr": "هَذَا الْكِتَابُ خَفِيفٌ.",
  "sentDe": "Dieses Buch ist leicht.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 69
 },
 {
  "id": "45800",
  "ar": "ثَقِيلٌ",
  "de": "schwer",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "ثَقِيلٌ",
  "pl": "ثِقَالٌ",
  "femSg": "ثَقِيلَةٌ",
  "femPl": "ثَقِيلَاتٌ",
  "root": "ث ق ل",
  "sentAr": "هَذَا الْحَجَرُ ثَقِيلٌ.",
  "sentDe": "Dieser Stein ist schwer.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 63
 },
 {
  "id": "45801",
  "ar": "وَرَقٌ",
  "de": "Papier",
  "type": "noun",
  "chapter": 3,
  "gender": "masculine",
  "sg": "وَرَقٌ",
  "pl": "أَوْرَاقٌ",
  "femSg": null,
  "femPl": null,
  "root": "و ر ق",
  "sentAr": "هَذَا وَرَقٌ نَظِيفٌ عَلَى الْمَكْتَبِ.",
  "sentDe": "Dies ist sauberes Papier auf dem Schreibtisch.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 76
 },
 {
  "id": "45802",
  "ar": "مَاءٌ",
  "de": "Wasser",
  "type": "noun",
  "chapter": 3,
  "gender": "masculine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "م و ه",
  "sentAr": "هَذَا مَاءٌ بَارِدٌ وَنَظِيفٌ.",
  "sentDe": "Dies ist kaltes und sauberes Wasser.",
  "quran": {
   "surah": "Al-Anbiya",
   "ayah": "21:30",
   "ar": "وَجَعَلْنَا مِنَ الْمَاءِ كُلَّ شَيْءٍ حَيٍّ",
   "de": "...und aus dem Wasser alles Lebendige gemacht.",
   "note": "Geprueft gegen quran.com."
  },
  "source": "vocabulary",
  "box": 5,
  "acc": 96
 },
 {
  "id": "45803",
  "ar": "تُفَّاحٌ",
  "de": "Apfel",
  "type": "noun",
  "chapter": 3,
  "gender": "masculine",
  "sg": "تُفَّاحٌ",
  "pl": "تَفَافِيحُ",
  "femSg": null,
  "femPl": null,
  "root": "ت ف ح",
  "sentAr": "هَذَا تُفَّاحٌ حُلْوٌ.",
  "sentDe": "Dies ist ein süßer Apfel.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 77
 },
 {
  "id": "45804",
  "ar": "دُكَّانٌ",
  "de": "Geschäft",
  "type": "noun",
  "chapter": 3,
  "gender": "masculine",
  "sg": "دُكَّانٌ",
  "pl": "دَكَاكِينُ",
  "femSg": null,
  "femPl": null,
  "root": "د ك ن",
  "sentAr": "هَذَا دُكَّانٌ صَغِيرٌ قَرِيبٌ مِنَ السُّوقِ.",
  "sentDe": "Dies ist ein kleines Geschäft nahe dem Markt.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 69
 },
 {
  "id": "45805",
  "ar": "جَمِيلٌ",
  "de": "schön",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "جَمِيلٌ",
  "pl": "جَمِيلُونَ",
  "femSg": "جَمِيلَةٌ",
  "femPl": "جَمِيلَاتٌ",
  "root": "ج م ل",
  "sentAr": "هَذَا الْبَيْتُ جَمِيلٌ.",
  "sentDe": "Dieses Haus ist schön.",
  "quran": {
   "surah": "Al-Muzzammil",
   "ayah": "73:10",
   "ar": "وَٱصْبِرْ عَلَىٰ مَا يَقُولُونَ وَٱهْجُرْهُمْ هَجْرًا جَمِيلًا",
   "de": "Und ertrage standhaft, was sie sagen, und meide sie auf schöne Weise",
   "note": null
  },
  "source": "vocabulary",
  "box": 5,
  "acc": 91
 },
 {
  "id": "45806",
  "ar": "حُلْوٌ",
  "de": "süß",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "حُلْوٌ",
  "pl": "حُلْوُونَ",
  "femSg": "حُلْوَةٌ",
  "femPl": "حُلْوَاتٌ",
  "root": "ح ل و",
  "sentAr": "هَذَا الشَّايُ حُلْوٌ.",
  "sentDe": "Dieser Tee ist süß.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 69
 },
 {
  "id": "45807",
  "ar": "مَرِيضٌ",
  "de": "krank",
  "type": "adjective",
  "chapter": 3,
  "gender": "masculine",
  "sg": "مَرِيضٌ",
  "pl": "مَرْضَى",
  "femSg": "مَرِيضَةٌ",
  "femPl": "مَرِيضَاتٌ",
  "root": "م ر ض",
  "sentAr": "الرَّجُلُ الْمَرِيضُ فِي الْمُسْتَشْفَى الْآنَ.",
  "sentDe": "Der kranke Mann ist jetzt im Krankenhaus.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 59
 },
 {
  "id": "45808",
  "ar": "مِنْ",
  "de": "von / aus",
  "type": "particle",
  "chapter": 4,
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "الطَّالِبُ مِنَ الْيَابَانِ.",
  "sentDe": "Der Student ist aus Japan.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 99
 },
 {
  "id": "45809",
  "ar": "إِلَى",
  "de": "nach / zu",
  "type": "particle",
  "chapter": 4,
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "مِنَ الْبَيْتِ إِلَى الْجَامِعَةِ.",
  "sentDe": "Vom Haus zur Universität.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 92
 },
 {
  "id": "45810",
  "ar": "أَيْنَ",
  "de": "wo",
  "type": "particle",
  "chapter": 4,
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "أَيْنَ الْمِفْتَاحُ؟",
  "sentDe": "Wo ist der Schlüssel?",
  "quran": {
   "surah": "At-Takwir",
   "ayah": "81:26",
   "ar": "فَأَيْنَ تَذْهَبُونَ",
   "de": "Wo geht ihr denn hin",
   "note": null
  },
  "source": "vocabulary",
  "box": 5,
  "acc": 90
 },
 {
  "id": "45811",
  "ar": "عَلَى",
  "de": "auf",
  "type": "particle",
  "chapter": 4,
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "الْقَلَمُ عَلَى الْمَكْتَبِ.",
  "sentDe": "Der Stift ist auf dem Schreibtisch.",
  "quran": {
   "surah": "As-Saffat",
   "ayah": "37:181",
   "ar": "وَسَلَٰمٌ عَلَى ٱلْمُرْسَلِينَ",
   "de": "Und Friede sei auf den Gesandten",
   "note": null
  },
  "source": "vocabulary",
  "box": 5,
  "acc": 95
 },
 {
  "id": "45812",
  "ar": "فِي",
  "de": "in",
  "type": "particle",
  "chapter": 4,
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "الْكِتَابُ فِي الْحَقِيبَةِ.",
  "sentDe": "Das Buch ist in der Tasche.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 98
 },
 {
  "id": "45813",
  "ar": "الْفِلِيبِّينُ",
  "de": "Philippinen",
  "type": "noun",
  "chapter": 4,
  "gender": "feminine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "ف ل ب",
  "sentAr": "هَذَا الطَّالِبُ مِنَ الْفِلِيبِّينِ.",
  "sentDe": "Dieser Student ist von den Philippinen.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 98
 },
 {
  "id": "45814",
  "ar": "الْيَابَانُ",
  "de": "Japan",
  "type": "noun",
  "chapter": 4,
  "gender": "feminine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "ي ب ن",
  "sentAr": "هَذِهِ سَيَّارَةٌ مِنَ الْيَابَانِ.",
  "sentDe": "Dies ist ein Auto aus Japan.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 95
 },
 {
  "id": "45815",
  "ar": "الصِّينُ",
  "de": "China",
  "type": "noun",
  "chapter": 4,
  "gender": "feminine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "ص ي ن",
  "sentAr": "هَذَا الْكُرْسِيُّ مِنَ الصِّينِ.",
  "sentDe": "Dieser Stuhl ist aus China.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 96
 },
 {
  "id": "45816",
  "ar": "الْهِنْدُ",
  "de": "Indien",
  "type": "noun",
  "chapter": 4,
  "gender": "feminine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "ه ن د",
  "sentAr": "هَذَا الشَّايُ مِنَ الْهِنْدِ.",
  "sentDe": "Dieser Tee ist aus Indien.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 93
 },
 {
  "id": "45817",
  "ar": "مَدْرَسَةٌ",
  "de": "Schule",
  "type": "noun",
  "chapter": 4,
  "gender": "feminine",
  "sg": "مَدْرَسَةٌ",
  "pl": "مَدَارِسُ",
  "femSg": null,
  "femPl": null,
  "root": "د ر س",
  "sentAr": "هَذِهِ مَدْرَسَةٌ نَظِيفَةٌ وَجَمِيلَةٌ.",
  "sentDe": "Dies ist eine saubere und schöne Schule.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 75
 },
 {
  "id": "45818",
  "ar": "سُوقٌ",
  "de": "Markt",
  "type": "noun",
  "chapter": 4,
  "gender": "feminine",
  "sg": "سُوقٌ",
  "pl": "أَسْوَاقٌ",
  "femSg": null,
  "femPl": null,
  "root": "س و ق",
  "sentAr": "هَذِهِ سُوقٌ قَدِيمَةٌ قَرِيبَةٌ مِنَ الْبَيْتِ.",
  "sentDe": "Dies ist ein alter Markt, nahe am Haus.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 63
 },
 {
  "id": "45819",
  "ar": "جَامِعَةٌ",
  "de": "Universität",
  "type": "noun",
  "chapter": 4,
  "gender": "feminine",
  "sg": "جَامِعَةٌ",
  "pl": "جَامِعَاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "ج م ع",
  "sentAr": "هَذِهِ جَامِعَةٌ مَشْهُورَةٌ.",
  "sentDe": "Dies ist eine berühmte Universität.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 66
 },
 {
  "id": "45820",
  "ar": "مُدِيرٌ",
  "de": "Direktor",
  "type": "noun",
  "chapter": 4,
  "gender": "masculine",
  "sg": "مُدِيرٌ",
  "pl": "مُدِيرُونَ",
  "femSg": "مُدِيرَةٌ",
  "femPl": "مُدِيرَاتٌ",
  "root": "د و ر",
  "sentAr": "الْمُدِيرُ فِي الْمَكْتَبِ الْآنَ.",
  "sentDe": "Der Direktor ist jetzt im Büro.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 68
 },
 {
  "id": "45821",
  "ar": "غُرْفَةٌ",
  "de": "Zimmer",
  "type": "noun",
  "chapter": 4,
  "gender": "feminine",
  "sg": "غُرْفَةٌ",
  "pl": "غُرَفٌ",
  "femSg": null,
  "femPl": null,
  "root": "غ ر ف",
  "sentAr": "هَذِهِ غُرْفَةٌ نَظِيفَةٌ.",
  "sentDe": "Dies ist ein sauberes Zimmer.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 72
 },
 {
  "id": "45822",
  "ar": "حَمَّامٌ",
  "de": "Badezimmer",
  "type": "noun",
  "chapter": 4,
  "gender": "masculine",
  "sg": "حَمَّامٌ",
  "pl": "حَمَّامَاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "ح م م",
  "sentAr": "هَذَا حَمَّامٌ نَظِيفٌ.",
  "sentDe": "Dies ist ein sauberes Badezimmer.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 98
 },
 {
  "id": "45823",
  "ar": "مَطْبَخٌ",
  "de": "Küche",
  "type": "noun",
  "chapter": 4,
  "gender": "masculine",
  "sg": "مَطْبَخٌ",
  "pl": "مَطَابِخُ",
  "femSg": null,
  "femPl": null,
  "root": "ط ب خ",
  "sentAr": "هَذَا مَطْبَخٌ صَغِيرٌ وَنَظِيفٌ.",
  "sentDe": "Dies ist eine kleine und saubere Küche.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 59
 },
 {
  "id": "45824",
  "ar": "سَمَاءٌ",
  "de": "Himmel",
  "type": "noun",
  "chapter": 4,
  "gender": "feminine",
  "sg": "سَمَاءٌ",
  "pl": "سَمَاوَاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "س م و",
  "sentAr": "النَّجْمُ فِي السَّمَاءِ.",
  "sentDe": "Der Stern ist am Himmel.",
  "quran": {
   "surah": "At-Tariq",
   "ayah": "86:1",
   "ar": "وَٱلسَّمَآءِ وَٱلطَّارِقِ",
   "de": "Beim Himmel und dem Pochenden",
   "note": null
  },
  "source": "vocabulary",
  "box": 4,
  "acc": 86
 },
 {
  "id": "45825",
  "ar": "فَصْلٌ",
  "de": "Klassenzimmer / Kapitel",
  "type": "noun",
  "chapter": 4,
  "gender": "masculine",
  "sg": "فَصْلٌ",
  "pl": "فُصُولٌ",
  "femSg": null,
  "femPl": null,
  "root": "ف ص ل",
  "sentAr": "هَذَا فَصْلٌ نَظِيفٌ فِي الْجَامِعَةِ.",
  "sentDe": "Dies ist ein sauberer Hörsaal an der Universität.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 79
 },
 {
  "id": "45826",
  "ar": "مِرْحَاضٌ",
  "de": "Toilette",
  "type": "noun",
  "chapter": 4,
  "gender": "masculine",
  "sg": "مِرْحَاضٌ",
  "pl": "مَرَاحِيضُ",
  "femSg": null,
  "femPl": null,
  "root": "ر ح ض",
  "sentAr": "أَيْنَ الْمِرْحَاضُ؟",
  "sentDe": "Wo ist die Toilette?",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 67
 },
 {
  "id": "45827",
  "ar": "رَسُولٌ",
  "de": "Gesandter",
  "type": "noun",
  "chapter": 5,
  "gender": "masculine",
  "sg": "رَسُولٌ",
  "pl": "رُسُلٌ",
  "femSg": null,
  "femPl": null,
  "root": "ر س ل",
  "sentAr": "هَذَا رَسُولٌ مَشْهُورٌ.",
  "sentDe": "Dies ist ein berühmter Gesandter.",
  "quran": {
   "surah": "Al-Fath",
   "ayah": "48:29",
   "ar": "مُحَمَّدٌ رَسُولُ اللَّهِ",
   "de": "Muhammad ist Allahs Gesandter.",
   "note": "Sehr bekannter Vers. Geprueft gegen quran.com."
  },
  "source": "vocabulary",
  "box": 5,
  "acc": 100
 },
 {
  "id": "45828",
  "ar": "تَحْتَ",
  "de": "unter",
  "type": "particle",
  "chapter": 5,
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "الْقِطُّ تَحْتَ السَّرِيرِ.",
  "sentDe": "Die Katze ist unter dem Bett.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 90
 },
 {
  "id": "45829",
  "ar": "عَمٌّ",
  "de": "Onkel väterlicherseits",
  "type": "noun",
  "chapter": 5,
  "gender": "masculine",
  "sg": "عَمٌّ",
  "pl": "أَعْمَامٌ",
  "femSg": null,
  "femPl": null,
  "root": "ع م م",
  "sentAr": "هَذَا عَمُّ الْوَلَدِ.",
  "sentDe": "Dies ist der Onkel des Jungen (väterlicherseits).",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 96
 },
 {
  "id": "45830",
  "ar": "اِبْنٌ",
  "de": "Sohn",
  "type": "noun",
  "chapter": 5,
  "gender": "masculine",
  "sg": "اِبْنٌ",
  "pl": "أَبْنَاءٌ",
  "femSg": null,
  "femPl": null,
  "root": "ب ن ي",
  "sentAr": "هَذَا اِبْنُ التَّاجِرِ.",
  "sentDe": "Dies ist der Sohn des Händlers.",
  "quran": {
   "surah": "Maryam",
   "ayah": "19:34",
   "ar": "ذَٰلِكَ عِيسَى ٱبْنُ مَرْيَمَۖ قَوْلَ ٱلْحَقِّ ٱلَّذِي فِيهِ يَمْتَرُونَ",
   "de": "Das ist ’Isa, der Sohn Maryams: (Es ist) das Wort der Wahrheit, woran sie zweifeln",
   "note": null
  },
  "source": "vocabulary",
  "box": 4,
  "acc": 88
 },
 {
  "id": "45831",
  "ar": "شَارِعٌ",
  "de": "Straße",
  "type": "noun",
  "chapter": 5,
  "gender": "masculine",
  "sg": "شَارِعٌ",
  "pl": "شَوَارِعُ",
  "femSg": null,
  "femPl": null,
  "root": "ش ر ع",
  "sentAr": "هَذَا شَارِعٌ طَوِيلٌ وَنَظِيفٌ.",
  "sentDe": "Dies ist eine lange und saubere Straße.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 73
 },
 {
  "id": "45832",
  "ar": "سَيَّارَةٌ",
  "de": "Auto",
  "type": "noun",
  "chapter": 5,
  "gender": "feminine",
  "sg": "سَيَّارَةٌ",
  "pl": "سَيَّارَاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "س ي ر",
  "sentAr": "هَذِهِ سَيَّارَةُ الْمُدِيرِ.",
  "sentDe": "Dies ist das Auto des Direktors.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 81
 },
 {
  "id": "45833",
  "ar": "كَعْبَةٌ",
  "de": "Kaaba",
  "type": "noun",
  "chapter": 5,
  "gender": "feminine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "ك ع ب",
  "sentAr": "هَذِهِ الْكَعْبَةُ قَدِيمَةٌ وَمَشْهُورَةٌ.",
  "sentDe": "Diese Kaaba ist alt und berühmt.",
  "quran": {
   "surah": "Al-Ma'idah",
   "ayah": "5:97",
   "ar": "جَعَلَ اللَّهُ الْكَعْبَةَ الْبَيْتَ الْحَرَامَ قِيَامًا لِلنَّاسِ",
   "de": "Allah hat die Ka'ba, das geschuetzte Haus, zu einer Staette des Gottesdienstes fuer die Menschen gemacht.",
   "note": "Ueber die Bedeutung der Kaaba. Geprueft gegen quran.com."
  },
  "source": "vocabulary",
  "box": 5,
  "acc": 98
 },
 {
  "id": "45834",
  "ar": "هُنَا",
  "de": "hier",
  "type": "particle",
  "chapter": 5,
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "الْمُدَرِّسُ هُنَا الْآنَ.",
  "sentDe": "Der Lehrer ist jetzt hier.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 81
 },
 {
  "id": "45835",
  "ar": "خَالٌ",
  "de": "Onkel mütterlicherseits",
  "type": "noun",
  "chapter": 5,
  "gender": "masculine",
  "sg": "خَالٌ",
  "pl": "أَخْوَالٌ",
  "femSg": null,
  "femPl": null,
  "root": "خ و ل",
  "sentAr": "هَذَا خَالُ الْبِنْتِ.",
  "sentDe": "Dies ist der Onkel des Mädchens (mütterlicherseits).",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 75
 },
 {
  "id": "45836",
  "ar": "هُنَاكَ",
  "de": "dort",
  "type": "particle",
  "chapter": 5,
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "الْمَكْتَبَةُ هُنَاكَ.",
  "sentDe": "Die Bibliothek ist dort.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 82
 },
 {
  "id": "45837",
  "ar": "مُغْلَقٌ",
  "de": "geschlossen",
  "type": "adjective",
  "chapter": 5,
  "gender": "masculine",
  "sg": "مُغْلَقٌ",
  "pl": "مُغْلَقُونَ",
  "femSg": "مُغْلَقَةٌ",
  "femPl": "مُغْلَقَاتٌ",
  "root": "غ ل ق",
  "sentAr": "بَابُ الدُّكَّانِ مُغْلَقٌ الْآنَ.",
  "sentDe": "Die Tür des Geschäfts ist jetzt geschlossen.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 61
 },
 {
  "id": "45838",
  "ar": "بِنْتٌ",
  "de": "Tochter / Mädchen",
  "type": "noun",
  "chapter": 5,
  "gender": "feminine",
  "sg": "بِنْتٌ",
  "pl": "بَنَاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "ب ن ت",
  "sentAr": "هَذِهِ بِنْتُ الْمُدَرِّسِ.",
  "sentDe": "Dies ist die Tochter des Lehrers.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 95
 },
 {
  "id": "45839",
  "ar": "اِسْمٌ",
  "de": "Name",
  "type": "noun",
  "chapter": 5,
  "gender": "masculine",
  "sg": "اِسْمٌ",
  "pl": "أَسْمَاءٌ",
  "femSg": null,
  "femPl": null,
  "root": "س م و",
  "sentAr": "مَا اِسْمُ هَذَا الْوَلَدِ؟",
  "sentDe": "Wie heißt dieser Junge? (Was ist der Name dieses Jungen?)",
  "quran": {
   "surah": "Al-'Alaq",
   "ayah": "96:1",
   "ar": "اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ",
   "de": "Lies im Namen deines Herrn, Der erschaffen hat.",
   "note": "Erster offenbarter Vers - auch Ursprung von Bismillah. Geprueft gegen quran.com."
  },
  "source": "vocabulary",
  "box": 5,
  "acc": 93
 },
 {
  "id": "45840",
  "ar": "حَقِيبَةٌ",
  "de": "Tasche / Rucksack",
  "type": "noun",
  "chapter": 5,
  "gender": "feminine",
  "sg": "حَقِيبَةٌ",
  "pl": "حَقَائِبُ",
  "femSg": null,
  "femPl": null,
  "root": "ح ق ب",
  "sentAr": "هَذِهِ حَقِيبَةُ الطَّالِبِ.",
  "sentDe": "Dies ist die Tasche des Studenten.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 55
 },
 {
  "id": "45841",
  "ar": "مِكْوَاةٌ",
  "de": "Bügeleisen",
  "type": "noun",
  "chapter": 6,
  "gender": "feminine",
  "sg": "مِكْوَاةٌ",
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "ك و ي",
  "sentAr": "هَذِهِ مِكْوَاةٌ جَدِيدَةٌ فِي الْمَطْبَخِ.",
  "sentDe": "Dies ist ein neues Bügeleisen in der Küche.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 57
 },
 {
  "id": "45842",
  "ar": "بَقَرَةٌ",
  "de": "Kuh",
  "type": "noun",
  "chapter": 6,
  "gender": "feminine",
  "sg": "بَقَرَةٌ",
  "pl": "بَقَرٌ / بَقَرَاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "ب ق ر",
  "sentAr": "هَذِهِ بَقَرَةٌ كَبِيرَةٌ.",
  "sentDe": "Dies ist eine große Kuh.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 88
 },
 {
  "id": "45843",
  "ar": "دَرَّاجَةٌ",
  "de": "Fahrrad",
  "type": "noun",
  "chapter": 6,
  "gender": "feminine",
  "sg": "دَرَّاجَةٌ",
  "pl": "دَرَّاجَاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "د ر ج",
  "sentAr": "هَذِهِ دَرَّاجَةٌ جَدِيدَةٌ وَسَرِيعَةٌ.",
  "sentDe": "Dies ist ein neues und schnelles Fahrrad.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 62
 },
 {
  "id": "45844",
  "ar": "مِلْعَقَةٌ",
  "de": "Löffel",
  "type": "noun",
  "chapter": 6,
  "gender": "feminine",
  "sg": "مِلْعَقَةٌ",
  "pl": "مَلَاعِقُ",
  "femSg": null,
  "femPl": null,
  "root": "ل ع ق",
  "sentAr": "هَذِهِ مِلْعَقَةٌ نَظِيفَةٌ.",
  "sentDe": "Dies ist ein sauberer Löffel.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 58
 },
 {
  "id": "45845",
  "ar": "فَلَّاحٌ",
  "de": "Bauer",
  "type": "noun",
  "chapter": 6,
  "gender": "masculine",
  "sg": "فَلَّاحٌ",
  "pl": "فَلَّاحُونَ",
  "femSg": "فَلَّاحَةٌ",
  "femPl": "فَلَّاحَاتٌ",
  "root": "ف ل ح",
  "sentAr": "هَذَا فَلَّاحٌ مُجْتَهِدٌ.",
  "sentDe": "Dies ist ein fleißiger Bauer.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 70
 },
 {
  "id": "45846",
  "ar": "أُمٌّ",
  "de": "Mutter",
  "type": "noun",
  "chapter": 6,
  "gender": "feminine",
  "sg": "أُمٌّ",
  "pl": "أُمَّهَاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "أ م م",
  "sentAr": "هَذِهِ أُمُّ الْبِنْتِ.",
  "sentDe": "Dies ist die Mutter des Mädchens.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 95
 },
 {
  "id": "45847",
  "ar": "أَبٌ",
  "de": "Vater",
  "type": "noun",
  "chapter": 6,
  "gender": "masculine",
  "sg": "أَبٌ",
  "pl": "آبَاءٌ",
  "femSg": null,
  "femPl": null,
  "root": "أ ب و",
  "sentAr": "هَذَا أَبٌ مُجْتَهِدٌ.",
  "sentDe": "Dies ist ein fleißiger Vater.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 97
 },
 {
  "id": "45848",
  "ar": "ثَلَّاجَةٌ",
  "de": "Kühlschrank",
  "type": "noun",
  "chapter": 6,
  "gender": "feminine",
  "sg": "ثَلَّاجَةٌ",
  "pl": "ثَلَّاجَاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "ث ل ج",
  "sentAr": "هَذِهِ ثَلَّاجَةٌ جَدِيدَةٌ فِي الْمَطْبَخِ.",
  "sentDe": "Dies ist ein neuer Kühlschrank in der Küche.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 62
 },
 {
  "id": "45849",
  "ar": "شَايٌ",
  "de": "Tee",
  "type": "noun",
  "chapter": 6,
  "gender": "masculine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "ش ا ي",
  "sentAr": "هَذَا شَايٌ حَارٌّ وَحُلْوٌ.",
  "sentDe": "Dies ist heißer und süßer Tee.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 79
 },
 {
  "id": "45850",
  "ar": "غَرْبٌ",
  "de": "Westen",
  "type": "noun",
  "chapter": 6,
  "gender": "masculine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "غ ر ب",
  "sentAr": "الْبَيْتُ فِي الْغَرْبِ.",
  "sentDe": "Das Haus ist im Westen.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 58
 },
 {
  "id": "45851",
  "ar": "قَهْوَةٌ",
  "de": "Kaffee",
  "type": "noun",
  "chapter": 6,
  "gender": "feminine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "ق ه و",
  "sentAr": "هَذِهِ قَهْوَةٌ حَارَّةٌ.",
  "sentDe": "Dies ist heißer Kaffee.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 83
 },
 {
  "id": "45852",
  "ar": "أَنْفٌ",
  "de": "Nase",
  "type": "noun",
  "chapter": 6,
  "gender": "masculine",
  "sg": "أَنْفٌ",
  "pl": "أُنُوفٌ",
  "femSg": null,
  "femPl": null,
  "root": "أ ن ف",
  "sentAr": "هَذَا أَنْفٌ صَغِيرٌ.",
  "sentDe": "Dies ist eine kleine Nase.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 61
 },
 {
  "id": "45853",
  "ar": "فَمٌ",
  "de": "Mund",
  "type": "noun",
  "chapter": 6,
  "gender": "masculine",
  "sg": "فَمٌ",
  "pl": "أَفْوَاهٌ",
  "femSg": null,
  "femPl": null,
  "root": "ف م",
  "sentAr": "هَذَا فَمٌ صَغِيرٌ.",
  "sentDe": "Dies ist ein kleiner Mund.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 72
 },
 {
  "id": "45854",
  "ar": "قِدْرٌ",
  "de": "Kochtopf",
  "type": "noun",
  "chapter": 6,
  "gender": "feminine",
  "sg": "قِدْرٌ",
  "pl": "قُدُورٌ",
  "femSg": null,
  "femPl": null,
  "root": "ق د ر",
  "sentAr": "هَذِهِ قِدْرٌ ثَقِيلَةٌ فِي الْمَطْبَخِ.",
  "sentDe": "Dies ist ein schwerer Kochtopf in der Küche.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 59
 },
 {
  "id": "45855",
  "ar": "أُذُنٌ",
  "de": "Ohr",
  "type": "noun",
  "chapter": 6,
  "gender": "feminine",
  "sg": "أُذُنٌ",
  "pl": "آذَانٌ",
  "femSg": null,
  "femPl": null,
  "root": "أ ذ ن",
  "sentAr": "هَذِهِ أُذُنٌ صَغِيرَةٌ.",
  "sentDe": "Dies ist ein kleines Ohr.",
  "quran": {
   "surah": "Al-Haqqah",
   "ayah": "69:12",
   "ar": "لِنَجْعَلَهَا لَكُمْ تَذْكِرَةً وَتَعِيَهَآ أُذُنٌ وَٰعِيَةٌ‏",
   "de": "um es für euch zu einer Erinnerung zu machen, und damit es von einem jeden aufnahmefähigen Ohr aufgenommen wird",
   "note": null
  },
  "source": "vocabulary",
  "box": 4,
  "acc": 80
 },
 {
  "id": "45856",
  "ar": "عَيْنٌ",
  "de": "Auge",
  "type": "noun",
  "chapter": 6,
  "gender": "feminine",
  "sg": "عَيْنٌ",
  "pl": "عُيُونٌ / أَعْيُنٌ",
  "femSg": null,
  "femPl": null,
  "root": "ع ي ن",
  "sentAr": "هَذِهِ عَيْنٌ جَمِيلَةٌ.",
  "sentDe": "Dies ist ein schönes Auge.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 90
 },
 {
  "id": "45857",
  "ar": "يَدٌ",
  "de": "Hand",
  "type": "noun",
  "chapter": 6,
  "gender": "feminine",
  "sg": "يَدٌ",
  "pl": "أَيْدٍ / أَيَادٍ",
  "femSg": null,
  "femPl": null,
  "root": "ي د ي",
  "sentAr": "هَذِهِ يَدُ الطَّبِيبِ.",
  "sentDe": "Dies ist die Hand des Arztes.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 82
 },
 {
  "id": "45858",
  "ar": "رِجْلٌ",
  "de": "Bein / Fuß",
  "type": "noun",
  "chapter": 6,
  "gender": "feminine",
  "sg": "رِجْلٌ",
  "pl": "أَرْجُلٌ",
  "femSg": null,
  "femPl": null,
  "root": "ر ج ل",
  "sentAr": "هَذِهِ رِجْلُ الْكُرْسِيِّ.",
  "sentDe": "Dies ist das Bein des Stuhls.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 84
 },
 {
  "id": "45859",
  "ar": "سَرِيعٌ",
  "de": "schnell",
  "type": "adjective",
  "chapter": 6,
  "gender": "masculine",
  "sg": "سَرِيعٌ",
  "pl": "سِرَاعٌ",
  "femSg": "سَرِيعَةٌ",
  "femPl": "سَرِيعَاتٌ",
  "root": "س ر ع",
  "sentAr": "هَذَا الْحِصَانُ سَرِيعٌ.",
  "sentDe": "Dieses Pferd ist schnell.",
  "quran": {
   "surah": "Al-Baqarah",
   "ayah": "2:202",
   "ar": "أُوْلَٰٓئِكَ لَهُمْ نَصِيبٌ مِّمَّا كَسَبُواْۚ وَٱللَّهُ سَرِيعُ ٱلْحِسَابِ",
   "de": "Für jene gibt es einen Anteil an dem, was sie verdient haben. Und Allah ist schnell im Abrechnen",
   "note": null
  },
  "source": "vocabulary",
  "box": 3,
  "acc": 65
 },
 {
  "id": "45860",
  "ar": "نَافِذَةٌ",
  "de": "Fenster",
  "type": "noun",
  "chapter": 6,
  "gender": "feminine",
  "sg": "نَافِذَةٌ",
  "pl": "نَوَافِذُ",
  "femSg": null,
  "femPl": null,
  "root": "ن ف ذ",
  "sentAr": "هَذِهِ نَافِذَةٌ مُغْلَقَةٌ فِي الْغُرْفَةِ.",
  "sentDe": "Dies ist ein geschlossenes Fenster im Zimmer.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 57
 },
 {
  "id": "45861",
  "ar": "شَرْقٌ",
  "de": "Osten",
  "type": "noun",
  "chapter": 6,
  "gender": "masculine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "ش ر ق",
  "sentAr": "الْمَسْجِدُ فِي الشَّرْقِ.",
  "sentDe": "Die Moschee ist im Osten.",
  "quran": null,
  "mnemo": "Als Gegenpaar lernen: شَرْقٌ (Osten) und غَرْبٌ (Westen) — beide stehen in deinen Vokabeln.",
  "source": "vocabulary",
  "box": 2,
  "acc": 49
 },
 {
  "id": "45862",
  "ar": "نَاقَةٌ",
  "de": "Kamelstute",
  "type": "noun",
  "chapter": 7,
  "gender": "feminine",
  "sg": "نَاقَةٌ",
  "pl": "نُوقٌ",
  "femSg": null,
  "femPl": null,
  "root": "ن و ق",
  "sentAr": "تِلْكَ نَاقَةٌ طَوِيلَةٌ.",
  "sentDe": "Das dort ist eine hohe Kamelstute.",
  "quran": {
   "surah": "Ash-Shams",
   "ayah": "91:13",
   "ar": "فَقَالَ لَهُمْ رَسُولُ ٱللَّهِ نَاقَةَ ٱللَّهِ وَسُقْيَٰهَا",
   "de": "Allahs Gesandter sagte zu ihnen: (Achtet auf) Allahs Kamelstute und ihre Trinkzeit",
   "note": null
  },
  "source": "vocabulary",
  "box": 3,
  "acc": 62
 },
 {
  "id": "45863",
  "ar": "بَطَّةٌ",
  "de": "Ente",
  "type": "noun",
  "chapter": 7,
  "gender": "feminine",
  "sg": "بَطَّةٌ",
  "pl": "بَطٌّ / بَطَّاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "ب ط ط",
  "sentAr": "تِلْكَ بَطَّةٌ صَغِيرَةٌ.",
  "sentDe": "Das dort ist eine kleine Ente.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 79
 },
 {
  "id": "45864",
  "ar": "مُمَرِّضَةٌ",
  "de": "Krankenschwester",
  "type": "noun",
  "chapter": 7,
  "gender": "feminine",
  "sg": "مُمَرِّضَةٌ",
  "pl": "مُمَرِّضَاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "م ر ض",
  "sentAr": "تِلْكَ مُمَرِّضَةٌ مُجْتَهِدَةٌ فِي الْمُسْتَشْفَى.",
  "sentDe": "Das dort ist eine fleißige Krankenschwester im Krankenhaus.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 79
 },
 {
  "id": "45865",
  "ar": "بَيْضَةٌ",
  "de": "Ei",
  "type": "noun",
  "chapter": 7,
  "gender": "feminine",
  "sg": "بَيْضَةٌ",
  "pl": "بَيْضٌ / بَيْضَاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "ب ي ض",
  "sentAr": "تِلْكَ بَيْضَةٌ بَارِدَةٌ.",
  "sentDe": "Das dort ist ein kaltes Ei.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 83
 },
 {
  "id": "45866",
  "ar": "مُؤَذِّنٌ",
  "de": "Gebetsrufer",
  "type": "noun",
  "chapter": 7,
  "gender": "masculine",
  "sg": "مُؤَذِّنٌ",
  "pl": "مُؤَذِّنُونَ",
  "femSg": null,
  "femPl": null,
  "root": "أ ذ ن",
  "sentAr": "هَذَا مُؤَذِّنٌ فِي الْمَسْجِدِ الْقَرِيبِ.",
  "sentDe": "Dies ist ein Gebetsrufer in der nahen Moschee.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 91
 },
 {
  "id": "45867",
  "ar": "دَجَاجَةٌ",
  "de": "Henne",
  "type": "noun",
  "chapter": 7,
  "gender": "feminine",
  "sg": "دَجَاجَةٌ",
  "pl": "دَجَاجٌ / دَجَاجَاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "د ج ج",
  "sentAr": "تِلْكَ دَجَاجَةٌ صَغِيرَةٌ.",
  "sentDe": "Das dort ist eine kleine Henne.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 89
 },
 {
  "id": "45868",
  "ar": "أَمْرِيكَا",
  "de": "Amerika",
  "type": "noun",
  "chapter": 8,
  "gender": "feminine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "أ م ر",
  "sentAr": "هَذَا الطَّبِيبُ مِنْ أَمْرِيكَا.",
  "sentDe": "Dieser Arzt ist aus Amerika.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 85
 },
 {
  "id": "45869",
  "ar": "سِكِّينٌ",
  "de": "Messer",
  "type": "noun",
  "chapter": 8,
  "gender": "masculine",
  "sg": "سِكِّينٌ",
  "pl": "سَكَاكِينُ",
  "femSg": null,
  "femPl": null,
  "root": "س ك ن",
  "sentAr": "هَذَا سِكِّينٌ حَادٌّ.",
  "sentDe": "Dies ist ein scharfes Messer.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 73
 },
 {
  "id": "45870",
  "ar": "أَلْمَانِيَا",
  "de": "Deutschland",
  "type": "noun",
  "chapter": 8,
  "gender": "feminine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "أ ل م",
  "sentAr": "هَذَا الطَّالِبُ مِنْ أَلْمَانِيَا.",
  "sentDe": "Dieser Student ist aus Deutschland.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 88
 },
 {
  "id": "45871",
  "ar": "إِنْجِلْتَرَا",
  "de": "England",
  "type": "noun",
  "chapter": 8,
  "gender": "feminine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "ا ن ج",
  "sentAr": "هَذِهِ السَّيَّارَةُ مِنْ إِنْجِلْتَرَا.",
  "sentDe": "Dieses Auto ist aus England.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 79
 },
 {
  "id": "45872",
  "ar": "الْعِرَاقُ",
  "de": "Irak",
  "type": "noun",
  "chapter": 8,
  "gender": "masculine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "ع ر ق",
  "sentAr": "هَذَا الرَّجُلُ مِنَ الْعِرَاقِ.",
  "sentDe": "Dieser Mann ist aus dem Irak.",
  "quran": null,
  "source": "vocabulary",
  "box": 5,
  "acc": 91
 },
 {
  "id": "45873",
  "ar": "سُوِيسْرَا",
  "de": "Schweiz",
  "type": "noun",
  "chapter": 8,
  "gender": "feminine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "س و س",
  "sentAr": "هَذَا الْمُدَرِّسُ مِنْ سُوِيسْرَا.",
  "sentDe": "Dieser Lehrer ist aus der Schweiz.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 77
 },
 {
  "id": "45874",
  "ar": "مُسْتَشْفًى",
  "de": "Krankenhaus",
  "type": "noun",
  "chapter": 8,
  "gender": "masculine",
  "sg": "مُسْتَشْفًى",
  "pl": "مُسْتَشْفَيَاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "ش ف ي",
  "sentAr": "هَذَا مُسْتَشْفًى نَظِيفٌ وَجَدِيدٌ.",
  "sentDe": "Dies ist ein sauberes und neues Krankenhaus.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 81
 },
 {
  "id": "45875",
  "ar": "فَاكِهَةٌ",
  "de": "Obst",
  "type": "noun",
  "chapter": 9,
  "gender": "feminine",
  "sg": "فَاكِهَةٌ",
  "pl": "فَوَاكِهُ",
  "femSg": null,
  "femPl": null,
  "root": "ف ك ه",
  "sentAr": "هَذِهِ فَاكِهَةٌ حُلْوَةٌ.",
  "sentDe": "Dies ist süßes Obst.",
  "quran": {
   "surah": "Al-Waqi'ah",
   "ayah": "56:32",
   "ar": "وَفَٰكِهَةٍ كَثِيرَةٍ‏",
   "de": "(bei) vielen Früchten",
   "note": null
  },
  "source": "vocabulary",
  "box": 3,
  "acc": 64
 },
 {
  "id": "45876",
  "ar": "عُصْفُورٌ",
  "de": "Spatz",
  "type": "noun",
  "chapter": 9,
  "gender": "masculine",
  "sg": "عُصْفُورٌ",
  "pl": "عَصَافِيرُ",
  "femSg": null,
  "femPl": null,
  "root": "ع ص ف",
  "sentAr": "هَذَا عُصْفُورٌ صَغِيرٌ جَمِيلٌ.",
  "sentDe": "Dies ist ein kleiner, schöner Spatz.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 58
 },
 {
  "id": "45877",
  "ar": "طَائِرٌ",
  "de": "Vogel",
  "type": "noun",
  "chapter": 9,
  "gender": "masculine",
  "sg": "طَائِرٌ",
  "pl": "طُيُورٌ",
  "femSg": null,
  "femPl": null,
  "root": "ط ي ر",
  "sentAr": "هَذَا طَائِرٌ جَمِيلٌ فِي السَّمَاءِ.",
  "sentDe": "Dies ist ein schöner Vogel am Himmel.",
  "quran": {
   "surah": "Al-Mulk",
   "ayah": "67:19",
   "ar": "أَوَلَمْ يَرَوْا إِلَى الطَّيْرِ فَوْقَهُمْ",
   "de": "Sehen sie denn nicht auf die Voegel ueber ihnen?",
   "note": "Korrigiert nach Pruefung gegen quran.com (vorher fehlerhaft zitiert)."
  },
  "source": "vocabulary",
  "box": 3,
  "acc": 51
 },
 {
  "id": "45878",
  "ar": "عَرَبِيَّةٌ",
  "de": "Arabisch",
  "type": "noun",
  "chapter": 9,
  "gender": "feminine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "ع ر ب",
  "sentAr": "اللُّغَةُ الْعَرَبِيَّةُ جَمِيلَةٌ.",
  "sentDe": "Die arabische Sprache ist schön.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 88
 },
 {
  "id": "45879",
  "ar": "لُغَةٌ",
  "de": "Sprache",
  "type": "noun",
  "chapter": 9,
  "gender": "feminine",
  "sg": "لُغَةٌ",
  "pl": "لُغَاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "ل غ و",
  "sentAr": "هَذِهِ لُغَةٌ صَعْبَةٌ وَجَمِيلَةٌ.",
  "sentDe": "Dies ist eine schwierige und schöne Sprache.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 68
 },
 {
  "id": "45880",
  "ar": "سَهْلٌ",
  "de": "leicht",
  "type": "adjective",
  "chapter": 9,
  "gender": "masculine",
  "sg": "سَهْلٌ",
  "pl": "سُهُولٌ",
  "femSg": "سَهْلَةٌ",
  "femPl": "سَهْلَاتٌ",
  "root": "س ه ل",
  "sentAr": "هَذَا الْكِتَابُ سَهْلٌ.",
  "sentDe": "Dieses Buch ist leicht.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 57
 },
 {
  "id": "45881",
  "ar": "مُجْتَهِدٌ",
  "de": "fleißig",
  "type": "adjective",
  "chapter": 9,
  "gender": "masculine",
  "sg": "مُجْتَهِدٌ",
  "pl": "مُجْتَهِدُونَ",
  "femSg": "مُجْتَهِدَةٌ",
  "femPl": "مُجْتَهِدَاتٌ",
  "root": "ج ه د",
  "sentAr": "هَذِهِ الطَّالِبَةُ مُجْتَهِدَةٌ.",
  "sentDe": "Diese Studentin ist fleißig.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 57
 },
 {
  "id": "45882",
  "ar": "مَشْهُورٌ",
  "de": "berühmt",
  "type": "adjective",
  "chapter": 9,
  "gender": "masculine",
  "sg": "مَشْهُورٌ",
  "pl": "مَشْهُورُونَ",
  "femSg": "مَشْهُورَةٌ",
  "femPl": "مَشْهُورَاتٌ",
  "root": "ش ه ر",
  "sentAr": "هَذَا الْمُدَرِّسُ مَشْهُورٌ.",
  "sentDe": "Dieser Lehrer ist berühmt.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 67
 },
 {
  "id": "45883",
  "ar": "إِنْجِلِيزِيَّةٌ",
  "de": "Englisch",
  "type": "noun",
  "chapter": 9,
  "gender": "feminine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "ا ن ج",
  "sentAr": "اللُّغَةُ الْإِنْجِلِيزِيَّةُ سَهْلَةٌ.",
  "sentDe": "Die englische Sprache ist leicht.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 66
 },
 {
  "id": "45884",
  "ar": "صَعْبٌ",
  "de": "schwierig",
  "type": "adjective",
  "chapter": 9,
  "gender": "masculine",
  "sg": "صَعْبٌ",
  "pl": "صِعَابٌ",
  "femSg": "صَعْبَةٌ",
  "femPl": "صَعْبَاتٌ",
  "root": "ص ع ب",
  "sentAr": "هَذَا الْكِتَابُ صَعْبٌ.",
  "sentDe": "Dieses Buch ist schwierig.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 56
 },
 {
  "id": "45885",
  "ar": "مَدِينَةٌ",
  "de": "Stadt",
  "type": "noun",
  "chapter": 9,
  "gender": "feminine",
  "sg": "مَدِينَةٌ",
  "pl": "مُدُنٌ",
  "femSg": null,
  "femPl": null,
  "root": "م د ن",
  "sentAr": "هَذِهِ مَدِينَةٌ بَعِيدَةٌ وَمَشْهُورَةٌ.",
  "sentDe": "Dies ist eine ferne und berühmte Stadt.",
  "quran": {
   "surah": "Al-Hijr",
   "ayah": "15:67",
   "ar": "وَجَآءَ أَهْلُ ٱلْمَدِينَةِ يَسْتَبْشِرُونَ",
   "de": "Und die Bewohner der Stadt kamen voller Freude",
   "note": null
  },
  "source": "vocabulary",
  "box": 4,
  "acc": 85
 },
 {
  "id": "45886",
  "ar": "الْقَاهِرَةُ",
  "de": "Kairo",
  "type": "noun",
  "chapter": 9,
  "gender": "feminine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "ق ه ر",
  "sentAr": "الْقَاهِرَةُ مَدِينَةٌ مَشْهُورَةٌ وَقَدِيمَةٌ.",
  "sentDe": "Kairo ist eine berühmte und alte Stadt.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 75
 },
 {
  "id": "45887",
  "ar": "يَوْمٌ",
  "de": "Tag",
  "type": "noun",
  "chapter": 9,
  "gender": "masculine",
  "sg": "يَوْمٌ",
  "pl": "أَيَّامٌ",
  "femSg": null,
  "femPl": null,
  "root": "ي و م",
  "sentAr": "هَذَا يَوْمٌ جَمِيلٌ.",
  "sentDe": "Dies ist ein schöner Tag.",
  "quran": {
   "surah": "Al-Fatiha",
   "ayah": "1:4",
   "ar": "مَالِكِ يَوْمِ الدِّينِ",
   "de": "Dem Herrscher am Tag des Gerichts.",
   "note": "Aus Al-Fatiha - jedem Muslim vertraut. Geprueft gegen quran.com."
  },
  "source": "vocabulary",
  "box": 4,
  "acc": 77
 },
 {
  "id": "45888",
  "ar": "لِمَاذَا",
  "de": "warum",
  "type": "particle",
  "chapter": 9,
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "لِمَاذَا هَذَا الْبَابُ مُغْلَقٌ؟",
  "sentDe": "Warum ist diese Tür geschlossen?",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 63
 },
 {
  "id": "45889",
  "ar": "كُوبٌ",
  "de": "Tasse / Becher / Trinkglas",
  "type": "noun",
  "chapter": 9,
  "gender": "masculine",
  "sg": "كُوبٌ",
  "pl": "أَكْوَابٌ",
  "femSg": null,
  "femPl": null,
  "root": "ك و ب",
  "sentAr": "هَذَا كُوبٌ صَغِيرٌ.",
  "sentDe": "Dies ist eine kleine Tasse.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 74
 },
 {
  "id": "45890",
  "ar": "مَكْتَبَةٌ",
  "de": "Bibliothek / Buchladen",
  "type": "noun",
  "chapter": 9,
  "gender": "feminine",
  "sg": "مَكْتَبَةٌ",
  "pl": "مَكْتَبَاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "ك ت ب",
  "sentAr": "هَذِهِ مَكْتَبَةٌ جَدِيدَةٌ قَرِيبَةٌ مِنَ الْجَامِعَةِ.",
  "sentDe": "Dies ist eine neue Bibliothek nahe der Universität.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 69
 },
 {
  "id": "45891",
  "ar": "الْآنَ",
  "de": "jetzt",
  "type": "particle",
  "chapter": 9,
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "الْمُدِيرُ فِي الْمَكْتَبِ الْآنَ.",
  "sentDe": "Der Direktor ist jetzt im Büro.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 73
 },
 {
  "id": "45892",
  "ar": "مُسْتَوْصَفٌ",
  "de": "Klinik / kleines Krankenhaus",
  "type": "noun",
  "chapter": 9,
  "gender": "masculine",
  "sg": "مُسْتَوْصَفٌ",
  "pl": "مُسْتَوْصَفَاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "و ص ف",
  "sentAr": "هَذَا مُسْتَوْصَفٌ صَغِيرٌ قَرِيبٌ مِنَ الْبَيْتِ.",
  "sentDe": "Dies ist eine kleine Klinik nahe dem Haus.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 63
 },
 {
  "id": "45893",
  "ar": "مِرْوَحَةٌ",
  "de": "Ventilator",
  "type": "noun",
  "chapter": 9,
  "gender": "feminine",
  "sg": "مِرْوَحَةٌ",
  "pl": "مَرَاوِحُ",
  "femSg": null,
  "femPl": null,
  "root": "ر و ح",
  "sentAr": "هَذِهِ مِرْوَحَةٌ قَدِيمَةٌ فِي الْغُرْفَةِ.",
  "sentDe": "Dies ist ein alter Ventilator im Zimmer.",
  "quran": null,
  "mnemo": "Das مِ am Anfang steht oft bei Geräten: مِفْتَاحٌ (Schlüssel), مِكْوَاةٌ (Bügeleisen), مِرْوَحَةٌ (Ventilator) — alle drei hast du schon.",
  "source": "vocabulary",
  "box": 2,
  "acc": 44
 },
 {
  "id": "45894",
  "ar": "الْكُوَيْتُ",
  "de": "Kuwait",
  "type": "noun",
  "chapter": 9,
  "gender": "masculine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "ك و ت",
  "sentAr": "هَذَا الرَّجُلُ مِنَ الْكُوَيْتِ.",
  "sentDe": "Dieser Mann ist aus Kuwait.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 65
 },
 {
  "id": "45895",
  "ar": "ثَانَوِيَّةٌ",
  "de": "weiterführende Schule",
  "type": "noun",
  "chapter": 9,
  "gender": "feminine",
  "sg": "ثَانَوِيَّةٌ",
  "pl": "ثَانَوِيَّاتٌ",
  "femSg": null,
  "femPl": null,
  "root": "ث ن ي",
  "sentAr": "هَذِهِ ثَانَوِيَّةٌ مَشْهُورَةٌ.",
  "sentDe": "Dies ist eine berühmte weiterführende Schule.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 53
 },
 {
  "id": "45896",
  "ar": "وَزِيرٌ",
  "de": "Minister",
  "type": "noun",
  "chapter": 9,
  "gender": "masculine",
  "sg": "وَزِيرٌ",
  "pl": "وُزَرَاءُ",
  "femSg": null,
  "femPl": null,
  "root": "و ز ر",
  "sentAr": "هَذَا وَزِيرٌ مَشْهُورٌ.",
  "sentDe": "Dies ist ein berühmter Minister.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 81
 },
 {
  "id": "45897",
  "ar": "حَادٌّ",
  "de": "scharf",
  "type": "adjective",
  "chapter": 9,
  "gender": "masculine",
  "sg": "حَادٌّ",
  "pl": "حَادُّونَ",
  "femSg": "حَادَّةٌ",
  "femPl": "حَادَّاتٌ",
  "root": "ح د د",
  "sentAr": "هَذَا السِّكِّينُ حَادٌّ وَجَدِيدٌ.",
  "sentDe": "Dieses Messer ist scharf und neu.",
  "quran": null,
  "source": "vocabulary",
  "box": 3,
  "acc": 62
 },
 {
  "id": "45898",
  "ar": "إِنْدُونِيسِيَا",
  "de": "Indonesien",
  "type": "noun",
  "chapter": 9,
  "gender": "feminine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "د و ن",
  "sentAr": "هَذَا الطَّالِبُ مِنْ إِنْدُونِيسِيَا.",
  "sentDe": "Dieser Student ist aus Indonesien.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 83
 },
 {
  "id": "48402",
  "ar": "الْيَوْمُ",
  "de": "heute",
  "type": "adjective",
  "chapter": 9,
  "gender": "masculine",
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": "ي و م",
  "sentAr": "الْمُدَرِّسُ هُنَا الْيَوْمَ.",
  "sentDe": "Der Lehrer ist heute hier.",
  "quran": null,
  "source": "vocabulary",
  "box": 4,
  "acc": 81
 },
 {
  "id": "59e30a8a-e400-4380-8adf-89e811852a1d",
  "ar": "لَحْمٌ",
  "de": "Fleisch",
  "type": "vocab",
  "chapter": "personal",
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "هَذَا لَحْمٌ فِي الثَّلَّاجَةِ.",
  "sentDe": "Dies ist Fleisch im Kühlschrank.",
  "quran": {
   "surah": "Al-Waqi'ah",
   "ayah": "56:21",
   "ar": "وَلَحْمِ طَيْرٍ مِّمَّا يَشْتَهُونَ",
   "de": "und Fleisch von Geflügel von dem, was sie begehren",
   "note": null
  },
  "mnemo": "Klanghilfe: „laḥm\" klingt an Lachs an — nur über den Klang gemerkt, nicht über die Herkunft.",
  "source": "personal_vocabulary",
  "note": null,
  "box": 1,
  "acc": null
 },
 {
  "id": "0f311405-7349-450c-885e-e3abefb6fbf3",
  "ar": "لِ",
  "de": "für / gehört",
  "type": "grammar",
  "chapter": "personal",
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "هَذَا الْكِتَابُ لِلْوَلَدِ.",
  "sentDe": "Dieses Buch gehört dem Jungen.",
  "quran": null,
  "mnemo": "Die Frage trägt die Antwort schon vorn: لِمَنْ؟ — لِ… („Für wen? — Für…\").",
  "source": "personal_vocabulary",
  "note": "Gehört zu حَرْفُ الْجَرِّ (Genitiv-Präposition)",
  "box": 1,
  "acc": null
 },
 {
  "id": "0e23a52d-e2f5-4a57-9082-58eb9f362d88",
  "ar": "أَيْضاً",
  "de": "auch / ebenfalls",
  "type": "vocab",
  "chapter": "personal",
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "الْبَيْتُ كَبِيرٌ، وَالْمَسْجِدُ كَبِيرٌ أَيْضاً.",
  "sentDe": "Das Haus ist groß, und die Moschee ist auch groß.",
  "quran": null,
  "mnemo": "Klanghilfe: „aiḍan\" klingt wie „ei, dann\" — auch das noch. Nur der Klang, keine Herkunft.",
  "source": "personal_vocabulary",
  "note": null,
  "box": 1,
  "acc": null
 },
 {
  "id": "397cfa89-5bc0-4ce7-ae45-30fe8ea64fe2",
  "ar": "اِسْمٌ مَجْرُورٌ",
  "de": "Nomen das in Genitiv steht",
  "type": "grammar",
  "chapter": "personal",
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "فِي الْبَيْتِ: «الْبَيْتِ» اِسْمٌ مَجْرُورٌ.",
  "sentDe": "In «fi al-bayti» ist «al-bayti» ein Nomen im Genitiv.",
  "quran": null,
  "mnemo": "Nie einzeln merken, immer als Paar: erst der حَرْف جَرّ, dann das اِسْم مَجْرُور — عَلَى طَعَامٍ.",
  "source": "personal_vocabulary",
  "note": "Wird ausgelöst durch: فِي، عَلَى، مِنْ، إِلَى",
  "box": 1,
  "acc": null
 },
 {
  "id": "36e01b96-9367-4f09-acaf-31a82bdcf061",
  "ar": "أَلْمُهَنْدِسٌ",
  "de": "Ingenieur",
  "type": "vocab",
  "chapter": "personal",
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "هَذَا مُهَنْدِسٌ مَشْهُورٌ.",
  "sentDe": "Dies ist ein berühmter Ingenieur.",
  "quran": null,
  "mnemo": "Wie مُدَرِّسٌ (Lehrer) fängt auch مُهَنْدِسٌ mit مُ an — beides Berufe, beide in deinen Vokabeln.",
  "source": "personal_vocabulary",
  "note": null,
  "box": 1,
  "acc": null
 },
 {
  "id": "65699a81-0913-4e3c-9d5d-fa750d972779",
  "ar": "الإِسْمُ",
  "de": "Nomen",
  "type": "grammar",
  "chapter": "personal",
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "«بَيْتٌ» هَذَا اِسْمٌ.",
  "sentDe": "«Baytun» - das ist ein Nomen.",
  "quran": null,
  "mnemo": "اِسْم ist das Wort für Name. Ein Nomen ist der Name einer Sache: Ding, Person, Ort.",
  "source": "personal_vocabulary",
  "note": null,
  "box": 1,
  "acc": null
 },
 {
  "id": "69179bbf-faa9-4b2a-859c-9e5f3d76b98c",
  "ar": "يَا",
  "de": "Rufpartikel",
  "type": "grammar",
  "chapter": "personal",
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "يَا وَلَدُ!",
  "sentDe": "Oh Junge! / He, Junge!",
  "quran": null,
  "mnemo": "يَا ist das „He!\" vor einem Namen — es ruft jemanden an, sonst nichts.",
  "source": "personal_vocabulary",
  "note": "Tanween fällt weg bei männlichen Namen",
  "box": 1,
  "acc": null
 },
 {
  "id": "c73787a3-8f9c-4033-b1ff-5644f34995d3",
  "ar": "مُضَافْ إِلَيْهِ",
  "de": "Besitzer",
  "type": "grammar",
  "chapter": "personal",
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "فِي «بَابُ الْبَيْتِ»: «الْبَيْتِ» هُوَ الْمُضَافُ إِلَيْهِ.",
  "sentDe": "In «die Tür des Hauses» ist «des Hauses» das Mudaf Ilayhi.",
  "quran": null,
  "mnemo": "Zwei Wörter, ein Besitz: das ERSTE ist der Besitz (مُضَاف), das ZWEITE der Besitzer (مُضَاف إِلَيْهِ) — كِتَابُ اللهِ, „das Buch Allahs\".",
  "source": "personal_vocabulary",
  "note": "Darf kein ال & Tanween haben. Kann jeden Fall annehmen",
  "box": 1,
  "acc": null
 },
 {
  "id": "d3cca272-90df-4963-a3dd-2653d009a77d",
  "ar": "إِثْنَانِ",
  "de": "Zwei (2)",
  "type": "vocab",
  "chapter": "personal",
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "كِتَابٌ، قَلَمٌ: اِثْنَانِ.",
  "sentDe": "Buch, Stift: zwei (Dinge).",
  "quran": null,
  "mnemo": "Zwei Silben für die Zwei: ith-nān. Klanghilfe: „ist’n Paar\".",
  "source": "personal_vocabulary",
  "note": null,
  "box": 1,
  "acc": null
 },
 {
  "id": "a540cdfa-cbaf-4d63-8250-b0b664d3b2b9",
  "ar": "صِفْرٌ",
  "de": "Null (0)",
  "type": "vocab",
  "chapter": "personal",
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "صِفْرٌ، وَاحِدٌ، اِثْنَانِ.",
  "sentDe": "Null, eins, zwei.",
  "quran": null,
  "mnemo": "Klanghilfe: „ṣifr\" klingt wie Ziffer — gemerkt wird der Klang, über die Herkunft wird hier nichts behauptet.",
  "source": "personal_vocabulary",
  "note": null,
  "box": 1,
  "acc": null
 },
 {
  "id": "c623f2fb-57a5-48b6-b176-55df461b2ada",
  "ar": "حَرْفُ الْجَرِّ",
  "de": "Genitiv-Präposition",
  "type": "grammar",
  "chapter": "personal",
  "gender": null,
  "sg": null,
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "«فِي، عَلَى، إِلَى، مِنْ، لِ» هِيَ حُرُوفُ جَرٍّ.",
  "sentDe": "Das sind die fünf Genitiv-Präpositionen.",
  "quran": null,
  "mnemo": "حَرْف heißt Partikel. Nach ihm steht immer ein اِسْم مَجْرُور — das Paar merken, nicht die Einzelteile.",
  "source": "personal_vocabulary",
  "note": "Z.B.: فِي، عَلَى، إِلَى، مِن",
  "box": 1,
  "acc": null
 },
 {
  "id": "50296",
  "ar": "وَاحِدٌ",
  "de": "eins",
  "type": "noun",
  "chapter": "personal",
  "gender": "masculine",
  "sg": "وَاحِدٌ",
  "pl": "وَاحِدَةٌ",
  "femSg": null,
  "femPl": null,
  "root": "و ح د",
  "past": null,
  "present": null,
  "imperative": null,
  "masdar": null,
  "sentAr": "كِتَابٌ: وَاحِدٌ.",
  "sentDe": "Buch: eins.",
  "quran": {
   "surah": "Al-Furqan",
   "ayah": "25:14",
   "ar": "لَّا تَدْعُواْ ٱلْيَوْمَ ثُبُورًا وَٰحِدًا وَٱدْعُواْ ثُبُورًا كَثِيرًا",
   "de": "„Ruft heute nicht nach (nur) einer einzigen Vernichtung, sondern ruft nach vielen Vernichtungen",
   "note": null
  },
  "note": null,
  "book": "madina-1",
  "source": "vocabulary"
 },
 {
  "id": "50297",
  "ar": "ثَلَاثَةٌ",
  "de": "drei",
  "type": "noun",
  "chapter": "personal",
  "gender": null,
  "sg": "ثَلَاثَةٌ",
  "pl": "ثَلَاثٌ",
  "femSg": null,
  "femPl": null,
  "root": "ث ل ث",
  "past": null,
  "present": null,
  "imperative": null,
  "masdar": null,
  "sentAr": "كِتَابٌ، قَلَمٌ، بَابٌ: ثَلَاثَةٌ.",
  "sentDe": "Buch, Stift, Tür: drei.",
  "note": null,
  "book": "madina-1",
  "source": "vocabulary"
 },
 {
  "id": "50298",
  "ar": "أَرْبَعَةٌ",
  "de": "vier",
  "type": "noun",
  "chapter": "personal",
  "gender": null,
  "sg": "أَرْبَعَةٌ",
  "pl": "أَرْبَعٌ",
  "femSg": null,
  "femPl": null,
  "root": "ر ب ع",
  "past": null,
  "present": null,
  "imperative": null,
  "masdar": null,
  "sentAr": "كِتَابٌ، قَلَمٌ، بَابٌ، سَرِيرٌ: أَرْبَعَةٌ.",
  "sentDe": "Buch, Stift, Tür, Bett: vier.",
  "note": null,
  "book": "madina-1",
  "source": "vocabulary"
 },
 {
  "id": "50299",
  "ar": "خَمْسَةٌ",
  "de": "fünf",
  "type": "noun",
  "chapter": "personal",
  "gender": null,
  "sg": "خَمْسَةٌ",
  "pl": "خَمْسٌ",
  "femSg": null,
  "femPl": null,
  "root": "خ م س",
  "past": null,
  "present": null,
  "imperative": null,
  "masdar": null,
  "sentAr": "ثَلَاثَةٌ، أَرْبَعَةٌ، خَمْسَةٌ.",
  "sentDe": "Drei, vier, fünf.",
  "note": null,
  "book": "madina-1",
  "source": "vocabulary"
 },
 {
  "id": "50300",
  "ar": "سِتَّةٌ",
  "de": "sechs",
  "type": "noun",
  "chapter": "personal",
  "gender": null,
  "sg": "سِتَّةٌ",
  "pl": "سِتٌّ",
  "femSg": null,
  "femPl": null,
  "root": "س ت ت",
  "past": null,
  "present": null,
  "imperative": null,
  "masdar": null,
  "sentAr": "أَرْبَعَةٌ، خَمْسَةٌ، سِتَّةٌ.",
  "sentDe": "Vier, fünf, sechs.",
  "note": null,
  "book": "madina-1",
  "source": "vocabulary"
 },
 {
  "id": "50301",
  "ar": "سَبْعَةٌ",
  "de": "sieben",
  "type": "noun",
  "chapter": "personal",
  "gender": null,
  "sg": "سَبْعَةٌ",
  "pl": "سَبْعٌ",
  "femSg": null,
  "femPl": null,
  "root": "س ب ع",
  "past": null,
  "present": null,
  "imperative": null,
  "masdar": null,
  "sentAr": "خَمْسَةٌ، سِتَّةٌ، سَبْعَةٌ.",
  "sentDe": "Fünf, sechs, sieben.",
  "quran": {
   "surah": "Al-Hijr",
   "ayah": "15:44",
   "ar": "لَهَا سَبْعَةُ أَبْوَٰبٍ لِّكُلِّ بَابٍ مِّنْهُمْ جُزْءٌ مَّقْسُومٌ",
   "de": "Sie hat sieben Tore, und jedem Tor wird ein Teil von ihnen zugewiesen",
   "note": null
  },
  "note": null,
  "book": "madina-1",
  "source": "vocabulary"
 },
 {
  "id": "50302",
  "ar": "ثَمَانِيَةٌ",
  "de": "acht",
  "type": "noun",
  "chapter": "personal",
  "gender": null,
  "sg": "ثَمَانِيَةٌ",
  "pl": "ثَمَانٍ",
  "femSg": null,
  "femPl": null,
  "root": "ث م ن",
  "past": null,
  "present": null,
  "imperative": null,
  "masdar": null,
  "sentAr": "سِتَّةٌ، سَبْعَةٌ، ثَمَانِيَةٌ.",
  "sentDe": "Sechs, sieben, acht.",
  "note": null,
  "book": "madina-1",
  "source": "vocabulary"
 },
 {
  "id": "50303",
  "ar": "تِسْعَةٌ",
  "de": "neun",
  "type": "noun",
  "chapter": "personal",
  "gender": null,
  "sg": "تِسْعَةٌ",
  "pl": "تِسْعٌ",
  "femSg": null,
  "femPl": null,
  "root": "ت س ع",
  "past": null,
  "present": null,
  "imperative": null,
  "masdar": null,
  "sentAr": "سَبْعَةٌ، ثَمَانِيَةٌ، تِسْعَةٌ.",
  "sentDe": "Sieben, acht, neun.",
  "quran": {
   "surah": "Al-Muddaththir",
   "ayah": "74:30",
   "ar": "عَلَيْهَا تِسْعَةَ عَشَرَ",
   "de": "Über ihr gibt es neunzehn (Wächter)",
   "note": null
  },
  "note": null,
  "book": "madina-1",
  "source": "vocabulary"
 },
 {
  "id": "50304",
  "ar": "عَشَرَةٌ",
  "de": "zehn",
  "type": "noun",
  "chapter": "personal",
  "gender": null,
  "sg": "عَشَرَةٌ",
  "pl": "عَشْرٌ",
  "femSg": null,
  "femPl": null,
  "root": "ع ش ر",
  "past": null,
  "present": null,
  "imperative": null,
  "masdar": null,
  "sentAr": "ثَمَانِيَةٌ، تِسْعَةٌ، عَشَرَةٌ.",
  "sentDe": "Acht, neun, zehn.",
  "note": null,
  "book": "madina-1",
  "source": "vocabulary"
 },

 /* ===== Aus dem Madina-Schluessel 1, nicht aus dem arabicroots-Abzug =====
    Die ersten zwei Eintraege dieser Herkunft. Elias hat sie am 30.07.2026
    freigegeben, nachdem aufgefallen war, dass sein Abzug اِبْنٌ und بِنْتٌ
    fuehrt, die beiden zugehoerigen Geschwister-Woerter aber nicht — obwohl sie
    im Schluessel in derselben Zeile stehen.

    Beleg, Schluessel 1, Lektion 6, Seite 22, woertlich:
      "Manche Substantive haben eine gesonderte weibliche Form z. B.
       اِبْن Sohn — أَخ Bruder / بِنْت Tochter — أُخْت Schwester"

    Warum "source": "madina-schluessel-1" und eine sprechende id: an der id muss
    man sehen, dass hier KEINE arabicroots-Nummer steht. Sonst sucht der naechste
    Abzugsvergleich nach einem Eintrag 50305, den es dort nie gab.

    Warum chapter 6 belegt ist und nicht geraten: dieselbe Seite 22 fuehrt die
    doppelten Koerperteile (يَد, رِجْل, عَيْن, أُذُن) ein, und die stehen im
    arabicroots-Abzug alle in Kapitel 6. Die Nummerierung von Schluessel und
    Abzug stimmt hier also ueberein.

    ⚠️ Die Vokalisierung ist am gerenderten Seitenbild abgelesen, nicht an der
    Textebene des PDF — die ist bei Schluessel 1 defekt und liefert falsch
    vokalisierte Woerter. Gelesen wurde: أَخٌ mit Fatha ueber dem Hamza und
    Dammatan auf dem خ · أُخْتٌ mit Damma ueber dem Hamza, Sukun auf dem خ und
    Dammatan auf dem ت.

    ⚠️ pl, root und Beispielsatz bleiben leer. Der Schluessel nennt sie an dieser
    Stelle nicht, und eine erfundene Pluralform waere ein Verstoss gegen E.1 —
    auch wenn sie "offensichtlich" scheint. Kommen sie in einer spaeteren Lektion
    vor, gehoeren sie belegt nachgetragen. */
 {
  "id": "madina1-l6-ach",
  "ar": "أَخٌ",
  "de": "Bruder",
  "type": "noun",
  "chapter": 6,
  "gender": "masculine",
  "sg": "أَخٌ",
  "pl": null,
  "femSg": "أُخْتٌ",
  "femPl": null,
  "root": null,
  "sentAr": "هَذَا أَخٌ وَهَذِهِ أُخْتٌ.",
  "sentDe": "Dies ist ein Bruder und dies ist eine Schwester.",
  "quran": null,
  "note": null,
  "book": "madina-1",
  "source": "madina-schluessel-1",
  "beleg": "Madina-Schluessel 1, Lektion 6, S. 22"
 },
 {
  "id": "madina1-l6-ucht",
  "ar": "أُخْتٌ",
  "de": "Schwester",
  "type": "noun",
  "chapter": 6,
  "gender": "feminine",
  "sg": "أُخْتٌ",
  "pl": null,
  "femSg": null,
  "femPl": null,
  "root": null,
  "sentAr": "الْأُخْتُ فِي الْبَيْتِ.",
  "sentDe": "Die Schwester ist im Haus.",
  "quran": null,
  "note": null,
  "book": "madina-1",
  "source": "madina-schluessel-1",
  "beleg": "Madina-Schluessel 1, Lektion 6, S. 22"
 }
];
